feat: update env and bin
Signed-off-by: pablon <73798198+pablon@users.noreply.github.com>

diff --git a/bin/install_kubie b/bin/install_kubie
--- a/bin/install_kubie
+++ b/bin/install_kubie
@@ -23,7 +23,7 @@ INSTALL_TARGET='/usr/local/bin'
 INSTALL_OPTS='--owner=root --group=root --mode=0755'
 
 # yay colors
-BOLD="\033[1;37m"
+STRONG="\033[1;37m"
 CYAN="\033[1;96m"
 GREEN="\033[1;92m"
 MAGENTA="\033[1;95m"
@@ -35,110 +35,110 @@ ME="$(basename ${0})"
 KUBIE_CONFIG="${HOME}/.kube/kubie.yaml"
 
 for program in curl jq; do
-  if ! (command -v ${program} &>/dev/null); then
-    echo -e "${RED}# program ${BOLD}${program}${RED} is needed to run this script.\n# Install it and try again.${NONE}\n"
-    exit 1
-  fi
+	if ! (command -v ${program} &>/dev/null); then
+		echo -e "${RED}# program ${STRONG}${program}${RED} is needed to run this script.\n# Install it and try again.${NONE}\n"
+		exit 1
+	fi
 done
 
 function get_latest_ver() {
-  if [[ "${i}" == "kubie" ]]; then
-    PROJECT="${GITHUB_PROJECT_KUBIE}"
-  elif [[ "${i}" == "fzf" ]]; then
-    PROJECT="${GITHUB_PROJECT_FZF}"
-  fi
-  LATEST="$(curl -s "https://api.github.com/repos/${PROJECT}/releases/latest" | jq -r ".tag_name")"
-  echo "${LATEST}"
+	if [[ "${i}" == "kubie" ]]; then
+		PROJECT="${GITHUB_PROJECT_KUBIE}"
+	elif [[ "${i}" == "fzf" ]]; then
+		PROJECT="${GITHUB_PROJECT_FZF}"
+	fi
+	LATEST="$(curl -s "https://api.github.com/repos/${PROJECT}/releases/latest" | jq -r ".tag_name")"
+	echo "${LATEST}"
 }
 
 function get_system() {
-  if [[ "$(uname)" == "Linux" ]]; then
-    export THIS_OS='linux'
-  elif [[ "$(uname)" == "Darwin" ]]; then
-    export THIS_OS='darwin'
-    if (! command -v brew &>/dev/null); then
-      echo -e "\n${YELLOW}Homebrew Package Manager for macOS is required to install kubie and fzf.${NONE}"
-      read -p "Install homebrew now? [Y/n]: " -s ANSWER
-      case "${ANSWER}" in
-      N | n)
-        echo "Bye"
-        exit 0
-        ;;
-      *)
-        echo "Installing Homebrew from https://brew.sh/"
-        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-        if [[ $? -ne 0 ]]; then
-          echo -e "${RED}ERROR installing homebrew${NONE}"
-          exit 1
-        fi
-        ;;
-      esac
-    fi
-  else
-    echo "${ME} only works on Linux and macOS. Bye."
-    exit 1
-  fi
-  if [ "$(uname -m)" != "x86_64" ]; then
-    echo "${ME} only works on x86_64. Bye."
-    exit 1
-  fi
+	if [[ "$(uname)" == "Linux" ]]; then
+		export THIS_OS='linux'
+	elif [[ "$(uname)" == "Darwin" ]]; then
+		export THIS_OS='darwin'
+		if (! command -v brew &>/dev/null); then
+			echo -e "\n${YELLOW}Homebrew Package Manager for macOS is required to install kubie and fzf.${NONE}"
+			read -p "Install homebrew now? [Y/n]: " -s ANSWER
+			case "${ANSWER}" in
+			N | n)
+				echo "Bye"
+				exit 0
+				;;
+			*)
+				echo "Installing Homebrew from https://brew.sh/"
+				bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+				if [[ $? -ne 0 ]]; then
+					echo -e "${RED}ERROR installing homebrew${NONE}"
+					exit 1
+				fi
+				;;
+			esac
+		fi
+	else
+		echo "${ME} only works on Linux and macOS. Bye."
+		exit 1
+	fi
+	if [ "$(uname -m)" != "x86_64" ]; then
+		echo "${ME} only works on x86_64. Bye."
+		exit 1
+	fi
 }
 
 function add_bash_completion() {
-  if [[ "$(echo $(basename ${SHELL}))" == "bash" ]] && [[ "${THIS_OS}" = "linux" ]] && [[ ! -f ~/.kube/kubie.bash ]]; then
-    echo -e "==> ${YELLOW}Installing kubie's shell completion${NONE} as ${BOLD}~/.kube/kubie.bash${NONE}"
-    curl -fsSL -o ~/.kube/kubie.bash 'https://raw.githubusercontent.com/sbstp/kubie/master/completion/kubie.bash'
-    echo -e "\n# Load kubie's bash completion\n[[ -f ~/.kube/kubie.bash ]] && source ~/.kube/kubie.bash\n" >>~/.bashrc
-  fi
+	if [[ "$(echo $(basename ${SHELL}))" == "bash" ]] && [[ "${THIS_OS}" = "linux" ]] && [[ ! -f ~/.kube/kubie.bash ]]; then
+		echo -e "==> ${YELLOW}Installing kubie's shell completion${NONE} as ${STRONG}~/.kube/kubie.bash${NONE}"
+		curl -fsSL -o ~/.kube/kubie.bash 'https://raw.githubusercontent.com/sbstp/kubie/master/completion/kubie.bash'
+		echo -e "\n# Load kubie's bash completion\n[[ -f ~/.kube/kubie.bash ]] && source ~/.kube/kubie.bash\n" >>~/.bashrc
+	fi
 }
 
 function install_update() {
-  get_system
-  WORKDIR="$(mktemp -d)" && cd ${WORKDIR}/ || exit 1
-  ACTION="${4}"
-  (
-    VERSION_CONTROL=off
-    case "${THIS_OS}" in
-    linux)
-      if [[ "${1}" = "kubie" ]]; then
-        curl -fSL --progress-bar -o ${1} "https://github.com/${GITHUB_PROJECT_KUBIE}/releases/download/${3}/${1}-${THIS_OS}-amd64"
-      elif [[ "${1}" = "fzf" ]]; then
-        curl -fSL --progress-bar -o ${1}.tgz "https://github.com/${GITHUB_PROJECT_FZF}/releases/download/${2}/${1}-${2}-${THIS_OS}_amd64.tar.gz" &&
-          tar xfz ${1}.tgz || exit 1
-      fi
-      sudo install ${INSTALL_OPTS} ${1} ${INSTALL_TARGET}/
-      ;;
-    darwin)
-      VERB="${ACTION:-install}"
-      echo -e "==> (${MAGENTA}invoking brew for ${VERB}...${NONE})"
-      if [[ "${1}" = "kubie" ]]; then
-        brew ${VERB} kubie
-      elif [[ "${1}" = "fzf" ]]; then
-        brew ${VERB} fzf
-      fi
-      ;;
-    esac
-  )
-  [[ -d ${WORKDIR} ]] && rm -rf "${WORKDIR}"
-  echo -e "> ${1} --version\n${GREEN}$(${1} --version)${NONE}\n"
+	get_system
+	WORKDIR="$(mktemp -d)" && cd ${WORKDIR}/ || exit 1
+	ACTION="${4}"
+	(
+		VERSION_CONTROL=off
+		case "${THIS_OS}" in
+		linux)
+			if [[ "${1}" = "kubie" ]]; then
+				curl -fSL --progress-bar -o ${1} "https://github.com/${GITHUB_PROJECT_KUBIE}/releases/download/${3}/${1}-${THIS_OS}-amd64"
+			elif [[ "${1}" = "fzf" ]]; then
+				curl -fSL --progress-bar -o ${1}.tgz "https://github.com/${GITHUB_PROJECT_FZF}/releases/download/${2}/${1}-${2}-${THIS_OS}_amd64.tar.gz" &&
+					tar xfz ${1}.tgz || exit 1
+			fi
+			sudo install ${INSTALL_OPTS} ${1} ${INSTALL_TARGET}/
+			;;
+		darwin)
+			VERB="${ACTION:-install}"
+			echo -e "==> (${MAGENTA}invoking brew for ${VERB}...${NONE})"
+			if [[ "${1}" = "kubie" ]]; then
+				brew ${VERB} kubie
+			elif [[ "${1}" = "fzf" ]]; then
+				brew ${VERB} fzf
+			fi
+			;;
+		esac
+	)
+	[[ -d ${WORKDIR} ]] && rm -rf "${WORKDIR}"
+	echo -e "> ${1} --version\n${GREEN}$(${1} --version)${NONE}\n"
 }
 
 function create_kubie_yaml() {
-  if [[ ! -d ${HOME}/.kube ]]; then # JIC...
-    mkdir -vp ${HOME}/.kube
-  fi
-  if (command -v zsh &>/dev/null); then
-    local KUBIE_SHELL='zsh'
-  else
-    local KUBIE_SHELL='bash'
-    add_bash_completion
-  fi
-  if [ -f ${KUBIE_CONFIG} ]; then
-    BACKUP_TS="$(date +%Y%m%d-%H%M%S)"
-    cp -vf ${KUBIE_CONFIG}{,.${BACKUP_TS}}
-    echo -e "==> ${YELLOW}Saving existing config file as${NONE} as ${MAGENTA}${KUBIE_CONFIG}.${BACKUP_TS}${NONE}"
-  fi
-  cat <<EOF >${KUBIE_CONFIG}
+	if [[ ! -d ${HOME}/.kube ]]; then # JIC...
+		mkdir -vp ${HOME}/.kube
+	fi
+	if (command -v zsh &>/dev/null); then
+		local KUBIE_SHELL='zsh'
+	else
+		local KUBIE_SHELL='bash'
+		add_bash_completion
+	fi
+	if [ -f ${KUBIE_CONFIG} ]; then
+		BACKUP_TS="$(date +%Y%m%d-%H%M%S)"
+		cp -vf ${KUBIE_CONFIG}{,.${BACKUP_TS}}
+		echo -e "==> ${YELLOW}Saving existing config file as${NONE} as ${MAGENTA}${KUBIE_CONFIG}.${BACKUP_TS}${NONE}"
+	fi
+	cat <<EOF >${KUBIE_CONFIG}
 # Force kubie to use a particular shell, if unset detect shell currently in use.
 # Possible values: bash, dash, fish, zsh
 # Default: unset
@@ -202,52 +202,52 @@ behavior:
     # Default: auto
     print_context_in_exec: auto
 EOF
-  if [ $? -eq 0 ]; then
-    echo -e "==> Configuration file ${YELLOW}${KUBIE_CONFIG}${NONE} created :-)"
-  else
-    echo -e "${RED}==> ERROR creating configuration file ${YELLOW}${KUBIE_CONFIG}${NONE} "
-  fi
+	if [ $? -eq 0 ]; then
+		echo -e "==> Configuration file ${YELLOW}${KUBIE_CONFIG}${NONE} created :-)"
+	else
+		echo -e "${RED}==> ERROR creating configuration file ${YELLOW}${KUBIE_CONFIG}${NONE} "
+	fi
 
-  if [[ ! -d ${HOME}/.kube/configs ]]; then
-    mkdir -vp ${HOME}/.kube/configs
-    echo -e "==> Now you can store every kubernetes context as a separate YAML file in \n\t${YELLOW}~/.kube/configs/${NONE} dir\n==> Then try running ${GREEN}kubie ctx${NONE}, then ${GREEN}kubie ns${NONE} and enjoy"
-  fi
+	if [[ ! -d ${HOME}/.kube/configs ]]; then
+		mkdir -vp ${HOME}/.kube/configs
+		echo -e "==> Now you can store every kubernetes context as a separate YAML file in \n\t${YELLOW}~/.kube/configs/${NONE} dir\n==> Then try running ${GREEN}kubie ctx${NONE}, then ${GREEN}kubie ns${NONE} and enjoy"
+	fi
 }
 
 # main
 for i in kubie fzf; do
-  [[ "${DEBUG}" -eq "1" ]] && echo -e " ${RED}==> Getting latest version of ${i}${NONE}"
-  LATEST_FULL="$(get_latest_ver ${i})"
-  LATEST="${LATEST_FULL/v/}"
-  [[ "${DEBUG}" -eq "1" ]] && echo -e " ${RED}==> LATEST_${i} =\t${LATEST}${NONE}"
+	[[ "${DEBUG}" -eq "1" ]] && echo -e " ${RED}==> Getting latest version of ${i}${NONE}"
+	LATEST_FULL="$(get_latest_ver ${i})"
+	LATEST="${LATEST_FULL/v/}"
+	[[ "${DEBUG}" -eq "1" ]] && echo -e " ${RED}==> LATEST_${i} =\t${LATEST}${NONE}"
 
-  if (which ${i} &>/dev/null); then
-    if [[ "${i}" = "kubie" ]]; then
-      CURRENT="$(kubie --version | awk '{print $2}')"
-    elif [[ "${i}" = "fzf" ]]; then
-      CURRENT="$(fzf --version | awk '{print $1}')"
-    fi
-    if [[ "${LATEST}" != "${CURRENT}" ]]; then
-      echo -e "==> ${YELLOW}${i} ${GREEN}needs to be updated${NONE}: ${BOLD}${CURRENT} => ${LATEST}${NONE}"
-      install_update ${i} ${LATEST} ${LATEST_FULL} upgrade
-    else
-      echo -e "==> ${YELLOW}${i}${NONE} already installed (${BOLD}${CURRENT} = latest${NONE})"
-    fi
-  else
-    echo -e "==> ${YELLOW}${i} ${BOLD}${LATEST}${GREEN} will be installed, hold on..${NONE}"
-    install_update ${i} ${LATEST} ${LATEST_FULL}
-  fi
+	if (which ${i} &>/dev/null); then
+		if [[ "${i}" = "kubie" ]]; then
+			CURRENT="$(kubie --version | awk '{print $2}')"
+		elif [[ "${i}" = "fzf" ]]; then
+			CURRENT="$(fzf --version | awk '{print $1}')"
+		fi
+		if [[ "${LATEST}" != "${CURRENT}" ]]; then
+			echo -e "==> ${YELLOW}${i} ${GREEN}needs to be updated${NONE}: ${STRONG}${CURRENT} => ${LATEST}${NONE}"
+			install_update ${i} ${LATEST} ${LATEST_FULL} upgrade
+		else
+			echo -e "==> ${YELLOW}${i}${NONE} already installed (${STRONG}${CURRENT} = latest${NONE})"
+		fi
+	else
+		echo -e "==> ${YELLOW}${i} ${STRONG}${LATEST}${GREEN} will be installed, hold on..${NONE}"
+		install_update ${i} ${LATEST} ${LATEST_FULL}
+	fi
 done
 
 if [ ! -r "${KUBIE_CONFIG}" ]; then
-  create_kubie_yaml
+	create_kubie_yaml
 else
-  echo -e "==> ${YELLOW}${KUBIE_CONFIG}${NONE} exists."
-  read -p "    Do you wan to update kubie's config file? [Y/n]:  "
-  case "${REPLY}" in
-  N | n) true ;;
-  *) create_kubie_yaml ;;
-  esac
+	echo -e "==> ${YELLOW}${KUBIE_CONFIG}${NONE} exists."
+	read -p "    Do you wan to update kubie's config file? [Y/n]:  "
+	case "${REPLY}" in
+	N | n) true ;;
+	*) create_kubie_yaml ;;
+	esac
 fi
 
 echo "==> All done ✅"
